# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pg_connect_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dconnect(object):
    def setupUi(self, dconnect):
        dconnect.setObjectName("dconnect")
        dconnect.resize(410, 318)
        self.gridLayout_2 = QtWidgets.QGridLayout(dconnect)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(dconnect)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lport = QtWidgets.QLineEdit(dconnect)
        self.lport.setObjectName("lport")
        self.gridLayout.addWidget(self.lport, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(dconnect)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.ldbname = QtWidgets.QLineEdit(dconnect)
        self.ldbname.setObjectName("ldbname")
        self.gridLayout.addWidget(self.ldbname, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(dconnect)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.luser = QtWidgets.QLineEdit(dconnect)
        self.luser.setObjectName("luser")
        self.gridLayout.addWidget(self.luser, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(dconnect)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lpass = QtWidgets.QLineEdit(dconnect)
        self.lpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lpass.setObjectName("lpass")
        self.gridLayout.addWidget(self.lpass, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(dconnect)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lhost = QtWidgets.QLineEdit(dconnect)
        self.lhost.setObjectName("lhost")
        self.gridLayout.addWidget(self.lhost, 4, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.licon = QtWidgets.QLabel(dconnect)
        self.licon.setMinimumSize(QtCore.QSize(140, 180))
        self.licon.setText("")
        self.licon.setObjectName("licon")
        self.horizontalLayout.addWidget(self.licon)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bconnect = QtWidgets.QPushButton(dconnect)
        self.bconnect.setMinimumSize(QtCore.QSize(100, 0))
        self.bconnect.setObjectName("bconnect")
        self.horizontalLayout_2.addWidget(self.bconnect)
        self.label_result = QtWidgets.QLabel(dconnect)
        self.label_result.setMinimumSize(QtCore.QSize(200, 0))
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_2.addWidget(self.label_result)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(dconnect)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(dconnect)
        self.buttonBox.accepted.connect(dconnect.accept)
        self.buttonBox.rejected.connect(dconnect.reject)
        QtCore.QMetaObject.connectSlotsByName(dconnect)

    def retranslateUi(self, dconnect):
        _translate = QtCore.QCoreApplication.translate
        dconnect.setWindowTitle(_translate("dconnect", "pg_connect"))
        self.label.setText(_translate("dconnect", "Port"))
        self.lport.setText(_translate("dconnect", "5432"))
        self.label_2.setText(_translate("dconnect", "Database name"))
        self.label_3.setText(_translate("dconnect", "User"))
        self.luser.setText(_translate("dconnect", "postgres"))
        self.label_5.setText(_translate("dconnect", "Password"))
        self.label_4.setText(_translate("dconnect", "Host"))
        self.lhost.setText(_translate("dconnect", "localhost"))
        self.bconnect.setText(_translate("dconnect", "Connect...."))
        self.label_result.setText(_translate("dconnect", "..............."))

